### PR TITLE
Configure database

### PR DESCRIPTION
**Pull request by mayrapena1324**
-  I refactored my code according to this resource. [https://hackersandslackers.com/flask-sqlalchemy-database-models/](url)
- My rehearsal view is still not complete. That will probably be my next branch and action item!

### CODE REVIEW

**Comment by barrywhart** [comment]
You don't want to commit `.pyc` files. Those are basically "compiled" versions of the `.py` files. You can help avoid doing this in the future by setting up a `.gitignore` file.

https://git-scm.com/docs/gitignore

This could be a good "sample`" `.gitignore` file for a Python project:
https://github.com/github/gitignore/blob/main/Python.gitignore

You can remove those files from the PR by using `git rm`, then committing and pushing.

**Review by barrywhart — COMMENTED** [review]
I'm not a Flask expert, but this looks good to me, other than the `.pyc` files and `.gitignore` stuff I mentioned.

**Review by barrywhart — APPROVED** [review]

**Comment by barrywhart** [comment]
The `.pyc` files aren't harmful, but they'll change anytime the corresponding `.py` file changes, which is distracting at best.

In general, there's a principal with git to try and avoid committing files that are "computer generated", and instead just commit the files used to _create_ those files. There are occasional exceptions to this, but it's a good rule of thumb.

**Comment by mayrapena1324** [comment]
I was able to remove the files. Bur somehow I ended up with a conflicting version of main. I think I might have accidentally pushed it to the master branch causing the conflict.

**Pull request merged**
